# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3740819c48e0ffd8b0c4f661a22172a5"
application_url = "https://logo-similar-barn-headphones.trycloudflare.com"
embedded = true
name = "HX Video Player"
handle = "hx-video-player-4"

[build]
include_config_on_deploy = true
dev_store_url = "hexagondigital.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_files, read_files"

[auth]
redirect_urls = [
  "https://logo-similar-barn-headphones.trycloudflare.com/auth/callback",
  "https://logo-similar-barn-headphones.trycloudflare.com/auth/shopify/callback",
  "https://logo-similar-barn-headphones.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
